
spring:
  redis:
    host: 127.0.0.1
    password:
    port: 6379
    timeout: 10000
    jedis:
      pool:
        max-idle: 8
        max-active: 8
        max-wait: -1
        min-idle: 0
  rabbitmq:
    host: 10.16.9.34
    port: 5672
    username: crm_rabbit_write
    password: crm_rabbit_write
    publisher-confirms: true
    virtual-host: crm
    listener:
      direct:
        acknowledge-mode: manual
      simple:
        acknowledge-mode: manual
server:
  port: 9898

evaluate:
  submit:
    success:
      aasf : b
      page-content: '{"defaultSceneCode":{"directJumpUrl":null,"nextPage":{"title":"感谢评价","subTitle":"","buttons":[{"buttonName":"","buttonUrl":""}]}},"JYPJ3":{"directJumpUrl":null}}'